### ISSUE TITLE
found invalid doi: doi:0.1034/j.1600-0587.2003.03443.x

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Plant-Pollinator-Web#1]
@millerse I was just scanning the GloBI ingestion logs and found an unresolved doi in this plant pollinator web dataset: 

doi:0.1034/j.1600-0587.2003.03443.x

Suggest to replace with: 

doi:10.1034/j.1600-0587.2003.03443.x

**Comment by millerse** [comment]
@jhpoelen Got it.

**Comment by jhpoelen** [comment]
@millerse thanks for fixing this in 61d8f3c11ee98306cd32c29379fc9fd8ae6dc84e . Closing issue.
